{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='posts', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000208DEB986D0>: Failed to resolve 'posts' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:07:29.752685Z", "metadata": {"source": "api5.log"}}
{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='posts', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000026923100610>: Failed to resolve 'posts' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:09:55.536513Z", "metadata": {"source": "api5.log"}}
{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='posts', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000192CFD82D90>: Failed to resolve 'posts' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:10:16.605138Z", "metadata": {"source": "api5.log"}}
{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='posts', port=443): Max retries exceeded with url: / (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000022775D92D90>: Failed to resolve 'posts' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:31:36.004733Z", "metadata": {"source": "api5.log"}}
